repos:
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.8.1
    hooks:
      - id: snakefmt
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

