name: Testing

on:
  push:
  pull_request:

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Testing
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--cores 2 --show-failed-logs --use-conda --conda-cleanup-pkgs cache'
          stagein: 'conda create -n eido eido; conda activate eido'
